### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by K1lldr0N85** [SoTrxII/marmiton-api#3]
Hi,

I'm currently working with marmiton-api. In your documentation we have this : 

```
import { searchRecipes, QueryBuilder, RECIPE_PRICE, RECIPE_DIFFICULTY } from 'marmiton-api'
// A query builder is provided to make complex queries
const query = qb
  .withTitleContaining('soja')
  .withoutOven()
  .withPrice(RECIPE_PRICE.CHEAP)
  .takingLessThan(45)
  .withDifficulty(RECIPE_DIFFICULTY.EASY)
  .build()
```

But in fact we have to do like this -> 

```
import { searchRecipes, MarmitonQueryBuilder, RECIPE_PRICE, RECIPE_DIFFICULTY } from 'marmiton-api';

import {Recipe} from "marmiton-api/dist/types/@types/recipe";

// A query builder is provided to make complex queries
const qb = new MarmitonQueryBuilder();
const query = qb
    .withTitleContaining('soja')
    .withoutOven()
    .withPrice(RECIPE_PRICE.CHEAP)
    .takingLessThan(45)
    .withDifficulty(RECIPE_DIFFICULTY.EASY)
    .build()

const recipes: Recipe[] = await searchRecipes(query, { limit: 48 })
```

Furthermore we got this issues : 

```
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (..............\node_modules\marmiton-api\src\marmiton-api.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by SoTrxII** [comment]
Hi,
The "usage" example is indeed wrong. I just updated it (and the parser itself).

For the second error, I kind of guess that you're trying to use this ES module in a commonjs env, hence the syntax error. 
I've added a commonjs bundle to the lib, this should do the trick.

On a side note, be aware that using this package on the client-side will lead to CORS issues, and it should be used on the server-side only. But I don't know if this applies to your situation.

**Comment by K1lldr0N85** [comment]
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (....................\node_modules\marmiton-api\src\marmiton-api.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
[nodemon] app crashed - waiting for file changes before starting...
```

im using your lib in a rest API in TS with express

Furthemore : 
![image](https://user-images.githubusercontent.com/35558846/139270560-aa730b3f-61c8-4534-b354-50c38e36d3cf.png)

**Comment by SoTrxII** [comment]
For the QueryBuilder, i'll remove it from the readme, missed that one, thank you.
For the error itself, honestly I can't reproduce it, even in typescript.
Could you provide a sample test app with this error ?  Or a least your env ?

**Comment by K1lldr0N85** [comment]
[test-marmiton-scrap.zip](https://github.com/SoTrxII/marmiton-api/files/7453139/test-marmiton-scrap.zip)

**Comment by SoTrxII** [comment]
Well I'm confused, this actually works fine for me. I've tried both by using nodemon or building the app and running it.
![image](https://user-images.githubusercontent.com/15107471/139673305-3ffee567-9cf5-4671-bdd3-00105dca9463.png)
What's your node version ? Mine is 16.9.1

**Comment by K1lldr0N85** [comment]
Nice, that was my node version !
Thanks
